server:
  port: 8090

spring:
# H2 Setting
  h2:
    console:
      enabled: true
      path: /h2
# Datasource Setting
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_UPPER=false;INIT=RUNSCRIPT FROM 'data-h2.sql'
    username: sa
    password: 
## Hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
# Eventuate Setting
eventuate.database.schema: testdb

eventuatelocal.kafka.bootstrap.servers: localhost:9092